---
name: Jason G.
surname: Wallace
position: "Associate Professor"
address: "Department of Crop & Soil Sciences, University of Georgia"
phone: +1-706-542-9696 
www: wallacelab.uga.edu
email: "jason.wallace@uga.edu"
#twitter: TheWallaceLab
github: jgwall
linkedin: "jason-wallace-a874b845"
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman       # Not bad, but a little ugly with title bar
header-includes:
  \definecolor{headcolor}{HTML}{000099}
  \usepackage{tabularx}
  \usepackage{float}
  \usepackage{colortbl}
  #\usepackage{xcolor}
#  \usepackage{booktabs}
#  \usepackage{longtable}
#  \usepackage{array}
#  \usepackage{multirow}
#  \usepackage{wrapfig}
  
#  
#  \usepackage{pdflscape}
#  \usepackage{tabu}
#  \usepackage{threeparttable}
#  \usepackage{threeparttablex}
#  \usepackage[normalem]{ulem}
#  \usepackage{makecell}
#  

# TODO: Can also use Bookdown to separate out sections. Not necessary as currently written, but would help if want to include plaint-text stuff somewhere.

# TODO: look at this forum post for splitting xtables over mult. pages:https://tex.stackexchange.com/questions/376790/tabularx-break-long-tables-over-several-pages  Maybe booktabs?
---

<!-- Formatting LaTeX commands -->
\renewcommand{\labelitemi}{\textbullet}  <!-- Reset bullets to round circles -->
\setlist{nosep,after=\vspace{-\baselineskip}}  <!-- Don't skip a line after lists finish -->



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(readr)
library(rcrossref)
library(tibble)
library(kableExtra)
library(bibtex)

# Function to make sure any special characters are dealt with first
sanitize = function(tbl){
  tbl %>% mutate_all(dplR::latexify, doublebackslash = FALSE)
}

# Helper function to load a CSV and do routine tasks
load_data = function(infile){
  read_csv(infile, show_col_types=FALSE) %>% sanitize
}

# Helper function to bold text
bold = function(x){
  paste("\\textbf{", x, "}", sep="")
}

# Function to produce very basic table, no lines or headings - From Rob Hyndman, https://github.com/robjhyndman/CV, with modifications
baretable <- function(tbl, digits = 0,
                      include.colnames = FALSE, include.rownames = FALSE,
                      hline.after = NULL, size = getOption("xtable.size", NULL),
                      add.to.row = getOption("xtable.add.to.row", NULL), 
                      tabular.environment="tabularx",
                      width = "\\textwidth",
                      ...) {
  xtable::xtable(tbl, digits = digits, ...) %>%
    print(
      include.colnames = include.colnames, include.rownames = include.rownames,
      hline.after = hline.after,  comment = FALSE,
      tabular.environment = tabular.environment,
      floating = FALSE, size = size, add.to.row = add.to.row,
      width=width,
      sanitize.text.function = function(x) {x}
    )
}


```


# Academic History
```{r header_info, results="asis"}
load_data("sources/0_header_info.csv") %>%
  mutate(info = bold(info)) %>%
  baretable()
```

## Education
```{r education, results="asis"}
load_data("sources/education.csv") %>%
  mutate(degree = bold(paste(degree, "\\textendash{}", location)), .keep="unused") %>%
  relocate(year, degree) %>%
  arrange(desc(year)) %>% # Arrange in descending order of Year
  baretable()
```

## Professional Experience
```{r employment, results="asis"}
load_data("sources/employment.csv") %>% 
  arrange(desc(stop)) %>%
  mutate(time=paste(start, "\\textendash{}", stop, sep=""),
         title=bold(title),
         location=paste(organization, " (", location, ")", sep=""), .keep="unused") %>%
  relocate(time, title) %>%
  baretable()
```


## Awards
```{r awards, results="asis"}
load_data("sources/awards.csv") %>%
  relocate(when) %>%
  mutate(award=bold(award)) %>%
  baretable(align=c("llXl"))
```

# Instruction

## Instructor of Record
```{r teaching_mine, results="asis"}
schedule_to_bullets=function(class, schedule){
  bullets = paste(" \\item", schedule, sep=" ", collapse=" ")
  bullets = paste("\\begin{itemize}", bullets, "\\end{itemize}")
  paste(unique(class), bullets)
}

# Load and format
load_data("sources/teaching_mine.csv")  %>% 
  mutate(class = bold(class), 
         credits=paste(credits, ifelse(credits==1, "credit", "credits"))) %>%
  group_by(code) %>%
  summarize(class = schedule_to_bullets(class, schedule), credits=unique(credits)) %>%
  baretable(align=c("llXl")) # Have to specify column width for bullets to work ("X" = variable, but still works)
```

## Guest Lectures
```{r teaching_guest, results="asis"}
load_data("sources/teaching_guest.csv") %>%
  mutate(description = paste(bold(title), " (", class, ")", sep=""), .keep="unused") %>%
  relocate(date) %>%
  baretable()
```

## Student Mentorship
```{r student_mentorship, results="asis"}
# Note: throws error if not saved to variable
students=load_data("sources/students_grads.csv") %>% 
  arrange(desc(year)) %>%  # Sort newest to oldest
  mutate(role = paste(role, " (", status, ")", sep=""), 
         name=bold(name),
         department = ifelse(is.na(notes), department, paste(department, " (", notes, ")", sep="")), #Add notes in if present
         .keep="unused") %>%
  relocate(degree, year) %>%
  group_by(role) %>%
  group_map(function(x, ...){
    cat("###", unique(x$role), "\n")
    x %>% select(-role) %>% 
      #baretable(align="llllX")
      baretable(align=c("l", "p{1.5em}", "p{5em}", "p{11em}", "X"))
  }, .keep=TRUE)
```

### Visiting Scientists
```{r visitors, results="asis"}
visitors = load_data("sources/visiting_scientists.csv") %>%
  mutate(name=bold(name)) %>%
  relocate(date) %>%
  baretable()
```

### Undergraduate Mentoring
```{r undergrads, results="asis"}
load_data("sources/students_undergrads.csv") %>%
  #mutate(name=bold(name)) %>%
  mutate(name=bold(name), role=paste(role, " (", university, ")", sep=""), .keep="unused") %>%
  relocate(date) %>%
  baretable()
```

### High School Students
```{r highschool, results="asis"}
load_data("sources/students_highschool.csv") %>%
  mutate(name=bold(name)) %>%
  select(-grade_level) %>%
  relocate(date, name) %>%
  baretable()
```

# Scholarly Activities

## Publications
```{r download_pubs, cache=TRUE, cache.extra = tools::md5sum('sources/publications.csv')}
# Load publications from CrossRef. Cache options mean only runs if source file or this chunk's code have changed
pubs = read.csv("sources/publications.csv")
citations = unlist(cr_cn(pubs$doi, format="bibtex"))
write(citations, "sources/publications.bib")
```


```{r load_pubs, results="asis"}
# Load publications into R
pubdata = read.csv("sources/publications.csv", row.names="doi", check.names=FALSE)
rownames(pubdata) = tolower(rownames(pubdata))
pubs = bibliography_entries("sources/publications.bib")
pubs = pubs %>% arrange(desc(issued)) %>%
  mutate(year=format(as.Date(issued), format="%Y"),
         DOI=tolower(DOI),
         period = pubdata[DOI, "period"],
         type = pubdata[DOI, "article_type"])
```

```{r summarize_pubs, results="asis"}
# Summary table of publications

# Table output; "hold_position" argument keeps it in place, not top of page
pub.summary = table(pubs$period, pubs$type) %>%
  as.data.frame.matrix() %>%
  relocate(research, review, book_chapter) %>%
  rename("Research Article"=research, Review=review, "Book Chapter"=book_chapter)
pub.summary = pub.summary[rev(unique(pubdata$period)),]
pub.totals = pub.summary %>%
  summarize_all(sum)
rownames(pub.totals) = "Total"
  
pub.summary %>% 
  rbind(pub.totals) %>%
  kbl(booktabs=TRUE) %>%
  kableExtra::kable_styling(latex_options = c("hold_position")) %>%
  row_spec(nrow(pub.summary), hline_after=TRUE) %>% # Separate from "totals"
  row_spec(nrow(pub.summary)+1, italic=TRUE, background="white", align="r") # Change format for "totals" row

```


```{r print_pubs, results="asis"}
# NOTE: only actually prints entries if printed in full elsewhere. Made workaround in next chunk.
for(myperiod in unique(pubs$period)){
  count = sum(pubs$period==myperiod)
  cat("### ", myperiod, " (", count, ")\n", sep="")
  pubs %>% filter(period==myperiod) %>%
    vitae:::knit_print.vitae_bibliography() %>%
    cat()
}
# TODO: Figure out how to indicate if I'm senior/corresponding author, bold my name, and underline lab members. (Latter two may have to be a lua filter apparnetly)
# TODO: More control if I do this myself (to add bold, asterisks, etc?). Harder to change bibliography method, so keep commented out if need that for some reason.
```

```{r print_pubs_dummy, include=FALSE}
# Workaround to needing a full printing for things to be included. 
# This doesn't show up, but it apparently gets everything placed properly to show
pubs 
```


<!-- # Publications Note: Can use rcrossref package to retrieve citations via API -->

<!-- ```{r} -->
<!-- #library(dplyr) -->
<!-- #knitr::write_bib(c("vitae", "tibble"), "packages.bib") -->

<!-- #bibliography_entries("packages.bib") %>% -->
<!-- #  arrange(desc(author$family), issued) -->
<!-- ``` -->

